### PR TITLE
Support Windows KB-SDK

### PR DESCRIPTION
**Pull request by sjyoo**
Requirements:
  - Java 1.7 or up
  - Docker Quickstart Terminal with Docker

### CODE REVIEW

**Comment by rsutormin** [comment]
@sjyoo: Hey Shinjae, I'm going to make some changes to your code. Don't you mind if I create PR to your fork?

**Comment by sjyoo** [comment]
No problems at all... please do it -SJ

**Comment by sjyoo** [comment]
Also, I expected you may need to reorganize the materials... -SJ

**Comment by rsutormin** [comment]
Here it is: https://github.com/sjyoo/kb_sdk/pull/1
Pay attention at last commit only. Other commits are just synchronization with last state of develop branch.
Can you please make sure these changes work for you on Windows? I had no chance to check it unfortunately.

**Comment by sjyoo** [comment]
Hi Roman,

I'll merge it but I doubt it would work under Cygwin because the way cmd
handling is specialized for Msys
but since we decided to support only docker terminal or Msys, I guess it is
fine...

I'll test it tomorrow early morning and make sure and then merge yours...

Thanks,
-SJ

**Comment by rsutormin** [comment]
Yeah, I think we should change
boolean isWindows = System.getProperty("os.name").startsWith("Windows");
to
boolean isWindows = System.getProperty("os.name").toLowerCase().contains("win");
It should work in Cygwin as well.

**Comment by sjyoo** [comment]
@rsutormin, it works well and please proceed to merge this PR.

**Pull request merged**
