### PR TITLE
Simplifying export declaration and adding strict/warnings

### PR DESCRIPTION
**Pull request by ialarmedalien**
Adding strict and warnings and simplifying the export declaration.

### CODE REVIEW

**Comment by MrCreosote** [comment]
this file is totally out of date - none of these urls even exist any more.

**Comment by MrCreosote** [comment]
BTW PRs should be made against the `develop` branch

**Comment by ialarmedalien** [comment]
The main reason for the PR was to check whether there was anything in [Erik's changes](https://github.com/kbase/kb_sdk/pull/344) that might have caused the travis tests to fail. The issue seems to be in [locating the appropriate jars](https://travis-ci.org/kbase/kb_sdk/builds/642619885#L355):

>  [javac] /home/travis/build/kbase/kb_sdk/src/java/us/kbase/catalog/AppClientGroup.java:7: error: package javax.annotation does not exist

Looking at the [PR history in travis](https://travis-ci.org/kbase/kb_sdk/pull_requests), the last successful build was 10 months ago, and had the same travis.yml file. The main (only) difference between that PR and the two most recent PRs is that the `kbase/jars` repo has been updated since then. Presumably there are changes in that repo that are now preventing the travis tests from passing because paths have altered, etc.

**Comment by MrCreosote** [comment]
I doubt it, jars are only added to the repo. I'm guessing that java 8 (maybe 9+? I forget) is now running, which doesn't have the annotation package built in.

In any case, from what I recall the travis tests hardly tested anything, and aren't a good indicator that a set of changes are groovy

**Comment by MrCreosote** [comment]
I looked at `travis.yml`. It barely tests anything

**Comment by ialarmedalien** [comment]
If it's a path / package installation problem, I assume it should be fairly easy to resolve by setting up the appropriate environment.

**Comment by MrCreosote** [comment]
Depends - could wind up peeling the onion as more issues from the java 8 -> java ? switch come to light. 

My advice would be to get the tests running with Java 8, which should fix the annotation package problem, and then see what else, if anything, is broken.

**Comment by ialarmedalien** [comment]
See https://github.com/kbase/kb_sdk/pull/346

**Pull request closed without merging**
