### PR TITLE
Split up README into separate doc files, made a Quick Start instead

### PR DESCRIPTION
**Pull request by dcchivian**

### CODE REVIEW

**Comment by dcchivian** [comment]
split up docs

**Comment by dcchivian** [comment]
added more links between docs

**Comment by psdehal** [comment]
Thanks Dylan, give me a little time to look this over. Does anyone else have comments?

**Comment by dcchivian** [comment]
added values to Data Type Table

**Comment by dcchivian** [comment]
removed "(MISSING)" labels from table (still present in kb_sdk_data_types.md) so that kb_sdk_data_types_table.md file can be considered basically done.

**Pull request merged**
