### PR TITLE
[WIP] Allow configuration of auth service

### PR DESCRIPTION
**Pull request by kkellerlbl**
Support configuration of an auth service endpoint in the configuration file.  The generated Service.pm will use the auth client library's default URL if not configured.

I've been testing this with my modifications to handle_service and it looks like it behaves okay.  It'd be helpful to have other eyes on it as well.

This PR goes to a new branch of kb_sdk, so merging won't break anything.  If it looks ok we can do another PR to develop.

### CODE REVIEW

**Comment by kkellerlbl** [comment]
Depends on https://github.com/kbase/auth/pull/31

**Comment by kkellerlbl** [comment]
We may also need to change the pointer for the auth submodule.

**Comment by MrCreosote** [comment]
@rsutormin should take a gander at this although it looks simple

**Comment by kkellerlbl** [comment]
Ping @rsutormin what do you think?

**Comment by rsutormin** [comment]
Sorry guys, I was busy lately. Do we support such config in python and java already? And what about tests?

**Comment by kkellerlbl** [comment]
I have not tried running Perl tests yet.

**Comment by kkellerlbl** [comment]
I want to run three different permutations of test.

1. Current codebase
2. These changes plus stock auth (should work, I think)
3. These changes plus Perl auth client changes in auth/dev-perl_auth branch

So far test 1. runs for a long time, so I may need to kill it and start again tomorrow.  3. is having problems, and I need to track down exactly what they are.  It's currently failing in testJavaAsyncService in AsyncDockerTest, which is odd because I didn't touch that code.  It may be a different issue.

**Comment by kkellerlbl** [comment]
Please do not merge

**Comment by kkellerlbl** [comment]
Still need more time to fix tests.  I'm closing till ready.

**Comment by kkellerlbl** [comment]
Please do not merge yet.

**Comment by kkellerlbl** [comment]
It's wrong anyway, there's a reference to one of my repos.

**Pull request closed without merging**
