### PR TITLE
Sync up the changes from njs_wrapper for CallbackServerConfigBuilder …

### PR DESCRIPTION
**Pull request by jayrbolton**
Sync up changes from an njs_wrapper PR (https://github.com/kbase/njs_wrapper/pull/113) for the duplicated code in in CallbackServerConfigBuilder and SubsequentCallRunner

### CODE REVIEW

**Comment by sychan** [comment]
Would Boris be a good person to review this as well?

**Comment by jayrbolton** [comment]
I'm going to investigate some of this code a little more (ie. DockerMountPoints).. I will close this PR for now so there's less stuff open

**Comment by jayrbolton** [comment]
I think this is worth merging so that the code doesn't diverge from njs_wrapper.
@bio-boris can you review? I'm syncing up the changes on:
* src/java/us/kbase/common/executionengine/CallbackServerConfigBuilder.java
* src/java/us/kbase/common/executionengine/SubsequentCallRunner.java

Which are duplicated between this repo and njs_wrapper.

I'm minimally adding params in:
* src/java/us/kbase/mobu/tester/ConfigLoader.java
* src/java/us/kbase/mobu/tester/SDKSubsequentCallRunner.java
* src/java/us/kbase/mobu/tester/test/CallbackServerTest.java
So that everything still compiles.

I haven't figured out how to use the refData related variables more intelligently in this repo. This PR can just serve as a minimalistic compatibility update to prevent the two codebases from diverging.

**Comment by jayrbolton** [comment]
I'm going to double check that these files look exactly the same on NJS and here and then will merge to `develop`.

**Pull request merged**
