### PR TITLE
fix python3 import

### PR DESCRIPTION
**Pull request by Tianhao-Gu**
@JamesJeffryes @jayrbolton 
Hi guys,
ConfigParser was renamed to configparser in Python3
https://docs.python.org/2/library/configparser.html#module-ConfigParser

### CODE REVIEW

**Comment by JamesJeffryes** [comment]
Where are you seeing these files used? I've always thought that they were no longer used

**Comment by Tianhao-Gu** [comment]
@JamesJeffryes hmmm maybe I wasn't doing it in a right way. In workspace test, I have to start a service locally. And I download this file to lib. Because Server.py does `from biokbase import log`

**Comment by JamesJeffryes** [comment]
Yeah, this is confusing. This file is in like 3 places but the one that get's included in the base SDK image (and thus the one Id recommend for you WS docks) is here: https://github.com/kbase/sdkbase2/blob/python/log.py

**Comment by Tianhao-Gu** [comment]
@JamesJeffryes ahh thanks. Closing ticket.

**Pull request closed without merging**
